version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    restart: always
    environment:
      GREETING: "Hello, World!"
    volumes:
      - ./files:/app/files
   
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
